CREATE TABLE TRAVEL (

    ID            INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    LOCATIONFROM  VARCHAR(30),
    LOCATIONTO    VARCHAR(30),
    PRICE	  DOUBLE,
    DEPARTUREDATE DATE);
	
	
CREATE TABLE TRAVEL_RESERVATION (

    ID_REC       INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FOREIGN KEY("ID_TRAVEL") REFERENCES TRAVEL("ID"),
    ID_TRAVEL    INT NOT NULL,
    NBPERSON     INT,
    TOTALPRICE   DOUBLE NOT NULL,
    DATE         DATE);

/*Insertions de tests*/
INSERT INTO TRAVEL (LOCATIONFROM,LOCATIONTO,PRICE,DEPARTUREDATE) VALUES ('Paris','Londres',13,'2010-12-01');
INSERT INTO TRAVEL (LOCATIONFROM,LOCATIONTO,PRICE,DEPARTUREDATE) VALUES ('Londres','Paris',33,'2010-12-02');
INSERT INTO TRAVEL (LOCATIONFROM,LOCATIONTO,PRICE,DEPARTUREDATE) VALUES ('Nantes','Londres',23,'2010-12-03');
INSERT INTO TRAVEL (LOCATIONFROM,LOCATIONTO,PRICE,DEPARTUREDATE) VALUES ('Londres','Nantes',33,'2010-12-04');
INSERT INTO TRAVEL (LOCATIONFROM,LOCATIONTO,PRICE,DEPARTUREDATE) VALUES ('Paris','Londres',13,'2010-12-05');
