CREATE TABLE MANIFESTATION (

    ID          INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TYPE        VARCHAR(30),
    NAME        VARCHAR(30),
    ADDRESS     VARCHAR(50),
    LOCATION    VARCHAR(30),
    PRICETICKET DOUBLE,
    DATE        DATE);

CREATE TABLE MANIFESTATION_RESERVATION (

    ID_REC      INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ID_MANIF    INT NOT NULL,
    FOREIGN KEY("ID_MANIF") REFERENCES MANIFESTATION("ID"),
    TOTALPRICE  DOUBLE NOT NULL,
    DATE	DATE);

/*Insertions de tests*/
INSERT INTO MANIFESTATION (TYPE,NAME,ADDRESS,LOCATION,PRICETICKET,DATE) VALUES ('opera','super opera','13 rue des tests','Paris',33,'2010-12-01');
INSERT INTO MANIFESTATION (TYPE,NAME,ADDRESS,LOCATION,PRICETICKET,DATE) VALUES ('concert','super concert','23 rue des tests','Paris',63,'2010-12-11');
INSERT INTO MANIFESTATION (TYPE,NAME,ADDRESS,LOCATION,PRICETICKET,DATE) VALUES ('opera','super opera','13 rue des tests','NANTES',33,'2010-12-01');
INSERT INTO MANIFESTATION (TYPE,NAME,ADDRESS,LOCATION,PRICETICKET,DATE) VALUES ('concert','super concert','23 rue des tests','NANTES',93,'2010-12-01');
INSERT INTO MANIFESTATION (TYPE,NAME,ADDRESS,LOCATION,PRICETICKET,DATE) VALUES ('daviscup','super final','65 rue des tests','Paris',133,'2010-12-11');