CREATE TABLE RESTAURANT (

    ID          INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    DESCRIPTION VARCHAR(30),
    NAME        VARCHAR(30),
    ADDRESS     VARCHAR(50),
    LOCATION    VARCHAR(30),
    STARS       INT,
    TYPEFOOD    VARCHAR(30),
    MENUPRICE   DOUBLE);

CREATE TABLE RESTAURANT_RESERVATION (

    ID_REC      INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ID_REST    INT NOT NULL,
    FOREIGN KEY("ID_REST") REFERENCES RESTAURANT("ID"),
    TOTALPRICE  DOUBLE NOT NULL,
    DATE        DATE NOT NULL);

/*Insertions de tests*/
INSERT INTO RESTAURANT (DESCRIPTION,NAME,ADDRESS,LOCATION,STARS,TYPEFOOD,MENUPRICE) VALUES ('super resto','ibis1','13 rue des tests','Paris',3,'gastro',33);
INSERT INTO RESTAURANT (DESCRIPTION,NAME,ADDRESS,LOCATION,STARS,TYPEFOOD,MENUPRICE) VALUES ('super resto','ibis2','23 rue des tests','Nantes',3,'gastro',34);
INSERT INTO RESTAURANT (DESCRIPTION,NAME,ADDRESS,LOCATION,STARS,TYPEFOOD,MENUPRICE) VALUES ('mal bouffe','mcDo','13 rue des mcdos','Paris',1,'rapide',9);
INSERT INTO RESTAURANT (DESCRIPTION,NAME,ADDRESS,LOCATION,STARS,TYPEFOOD,MENUPRICE) VALUES ('mal bouffe','mcDo','23 rue des mcdos','Nantes',1,'rapide',9);
INSERT INTO RESTAURANT (DESCRIPTION,NAME,ADDRESS,LOCATION,STARS,TYPEFOOD,MENUPRICE) VALUES ('super resto','ibis3','33 rue des tests','Paris',3,'gastro',43);